# Generated by Django 2.0.9 on 2018-12-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previoussearch',
            name='searched_by',
        ),
    ]
